### ISSUE TITLE
Activity com.uber.sdk.android.core.auth.LoginActivity has leaked ServiceConnection

### ISSUE THREAD

**Issue by AmitPrajapati1902** [uber/rides-android-sdk#171]
com.onusrides.onus.dev E/ActivityThread: Activity com.uber.sdk.android.core.auth.LoginActivity has leaked ServiceConnection com.uber.sdk.android.core.utils.CustomTabsHelper$1@138a1c2 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.uber.sdk.android.core.auth.LoginActivity has leaked ServiceConnection com.uber.sdk.android.core.utils.CustomTabsHelper$1@138a1c2 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1478)
        at android.app.ContextImpl.bindService(ContextImpl.java:1450)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
        at androidx.browser.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:73)
        at com.uber.sdk.android.core.utils.CustomTabsHelper.openCustomTab(CustomTabsHelper.java:84)
        at com.uber.sdk.android.core.auth.LoginActivity.loadChrometab(LoginActivity.java:281)
        at com.uber.sdk.android.core.auth.LoginActivity.loadWebPage(LoginActivity.java:244)
        at com.uber.sdk.android.core.auth.LoginActivity.loadUrl(LoginActivity.java:230)
        at com.uber.sdk.android.core.auth.LoginActivity.init(LoginActivity.java:198)
        at com.uber.sdk.android.core.auth.LoginActivity.onCreate(LoginActivity.java:169)
        at android.app.Activity.performCreate(Activity.java:6672)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by maekeshtwilightsoftwares** [comment]
is anyone resolved this issue?
