### ISSUE TITLE
LoginActivity crash consistently on 0.10.2

### ISSUE THREAD

**Issue by coyarzun89** [uber/rides-android-sdk#179]
Device: Google Pixel 2
Android Version: 10
Library version: 0.10.2

When I try to do login using the sdk, the **com.uber.sdk.android.core.auth.LoginActivity** crash consistently on the onDestroy method. I'm successfully receiving the access token, but because of the crash, my app also is closed:
```
@Override
    protected void onDestroy() {
        super.onDestroy();
        customTabsHelper.onDestroy(this);   <---- This is the line
    }
```
**It doesn't happen with the previous version 0.10.1**

I'm calling the login method by myself on the onClickListener:
```
configuration = SessionConfiguration.Builder()
                .setClientId(CLIENT_ID)
                .setRedirectUri(REDIRECT_URI)
                .setCustomScopes(Arrays.asList(CUSTOM_SCOPE))
                .build()

accessTokenStorage = AccessTokenManager(this)

loginManager = LoginManager(accessTokenStorage,
                this,
                configuration,
                LOGIN_BUTTON_CUSTOM_REQUEST_CODE)

loginManager.login(this)
```

This is the logcat
```
java.lang.RuntimeException: Unable to destroy activity {com.cornershopapp.android.debug/com.uber.sdk.android.core.auth.LoginActivity}: java.lang.IllegalArgumentException: connection is null
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4941)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4970)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: connection is null
        at android.app.ContextImpl.unbindService(ContextImpl.java:1773)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
        at com.uber.sdk.android.core.utils.CustomTabsHelper.onDestroy(CustomTabsHelper.java:100)
        at com.uber.sdk.android.core.auth.LoginActivity.onDestroy(LoginActivity.java:205)
        at android.app.Activity.performDestroy(Activity.java:8071)
```

Expected Behavior:
It shouldn't crash

**Comment by lalwani** [comment]
Have you set `REDIRECT_URI` properly in the gradle properties file for your project?
The format for `REDIRECT_URI` is `${applicationId}.uberauth://redirect`

**Comment by coyarzun89** [comment]
Yes, I'm using that same format. As i said before, with the same setup it works fine in version 0.10.1, but it crashes in version 0.10.2

**Comment by ValleZ** [comment]
A fix was merged
