### ISSUE TITLE
implement Uber sdk with android project use compileSdkVersion less than 23

### ISSUE THREAD

**Issue by ahmed-hamdy90** [uber/rides-android-sdk#38]
my android project compile using android sdk version 22 and I forced to upgrade my project's `CompileSdkversion` from 22 to 23 for using Uber sdk with it.

Even when I exclude `appcompat-v7` module in `build.gradle` file
```
    compile ('com.uber.sdk:rides-android:0.5.1') {
        exclude module: 'appcompat-v7'
    }
```
uber sdk crash As `RideRequestActivity.class` use `ContextCompat.checkSelfPermission` and `ActivityCompat.requestPermissions` methods

>          
java.lang.NoSuchMethodError: No static method checkSelfPermission(Landroid/content/Context;Ljava/lang/String;)I in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/data/com.yelllow.ubertest/files/instant-run/dex/slice-com.android.support-support-v4-22.2.0_08bdc58da7fbfec268d23acce14c9dbd98584614-classes.dex)
                                                                          at com.uber.sdk.android.rides.RideRequestActivity.onCreate(RideRequestActivity.java:142)
                                                                          at android.app.Activity.performCreate(Activity.java:6283)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:145)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

Is there any way to use Uber sdk with `compileSdkVersion` less than 23 ??

**Comment by tyvsmith** [comment]
Hey Ahmed. The Uber SDK requires using an up to date compileSdkVersion and targetSdkVersion because of the dependency on AppCompat which enforces this contract.

As Google recommends using an up to date version for both of these, what reasons would you have for not updating?

**Comment by tyvsmith** [comment]
Closing due to no response.

**Comment by ahmed-hamdy90** [comment]
@tyvsmith Sorry for not response, 
now I can't update my compileSdkVersion As I need to handle run time permissions ([dangerous permissions](https://developer.android.com/training/permissions/index.html)) begin from compileSdkVersion 23 [Android 6.0].

I had work with Uber web service instead of  Uber SDK.
