### ISSUE TITLE
throwing java.lang.NullPointerException: Must set pick up point latitude in RideParameters. when selected setPickupToMyLocation() instead of setPickupLocation(lat,long,name,address)

### ISSUE THREAD

**Issue by riyase** [uber/rides-android-sdk#44]
i want to make my pickup location as current location.. is that the purpose of setPickupToMyLocation() ?

**Comment by tyvsmith** [comment]
Thanks for reporting. Please provide a snippet of your integration code and the error log generated.

**Comment by riyase** [comment]
i was trying request-button-sample in samples folder in "rides-android-sdk-master".
i have changed the code like this:
(commented setProductId(), setPickupLocation() and added setPickupTOMyLocation() )

`RideParameters rideParametersForProduct = new RideParameters.Builder()
                /*.setProductId(UBERX_PRODUCT_ID)*/
                /*.setPickupLocation(PICKUP_LAT, PICKUP_LONG, PICKUP_NICK, PICKUP_ADDR)*/
                .setPickupToMyLocation()
                .setDropoffLocation(DROPOFF_LAT, DROPOFF_LONG, DROPOFF_NICK, DROPOFF_ADDR)
                .build();`

Error Log:
FATAL EXCEPTION: main
                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.uber.sdk.android.rides.samples/com.uber.sdk.android.rides.samples.SampleActivity}: java.lang.NullPointerException: Must set pick up point latitude in RideParameters.
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2308)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362)
                                                                                        at android.app.ActivityThread.access$700(ActivityThread.java:168)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                        at android.os.Looper.loop(Looper.java:177)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5493)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
                                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                                     Caused by: java.lang.NullPointerException: Must set pick up point latitude in RideParameters.
                                                                                        at com.uber.sdk.rides.client.utils.Preconditions.checkNotNull(Preconditions.java:82)
                                                                                        at com.uber.sdk.android.rides.internal.RideRequestButtonController.loadRideInformation(RideRequestButtonController.java:90)
                                                                                        at com.uber.sdk.android.rides.RideRequestButton.loadRideInformation(RideRequestButton.java:177)
                                                                                        at com.uber.sdk.android.rides.samples.SampleActivity.onCreate(SampleActivity.java:108)
                                                                                        at android.app.Activity.performCreate(Activity.java:5372)
                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362) 
                                                                                        at android.app.ActivityThread.access$700(ActivityThread.java:168) 
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                        at android.os.Looper.loop(Looper.java:177) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5493) 
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                        at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041) 
                                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by itstexter** [comment]
Fixed in [v0.5.4](https://github.com/uber/rides-android-sdk/releases/tag/v0.5.4)

**Comment by Dgilliams** [comment]
lol love that this was fixed 4 hours before I needed it!
